cleaning:
  min_sentence_character_length: 15
  max_sentence_length: 128
  sentence_delim: "[.:]"
  remove_characters: '[^-.,:\sA-z0-9]+'
  replace_characters:
    1: ["[0-9]{3,}", "###"]
    2: ["[0-9]{2}", "##"]
    3: ["[0-9]", "#"]
    4: ['\s{2,}', " "]
  write_mode: w
transformation:
  instructions:
    - "Rewrite this Dutch radiology text and structure it as a pointwise summary for the cardiologist"
    - "We want to know whether a radiologist identifies macrovascular/functional disease. Extract the label: macrovascular disease / functional disease / NO vascular disease / not related to cardiology. \n Macrovascular disease: any confirmation of significant stenosis or significant occlusion, explicit mentioning of vascular disease, any mentioning of a previous vascular intervention like stents/PTCA etc, any advise for a follow up diagnosis like angiogram or a vascular intervention \n Functional disease: any confirmation of ischemia, functional flow problems or cardiomyopathy, or an advise to perform e.g. a . \n No vascular disease: any mentioning of a clean scan, or no special findings. Not related to cardiology: e.g. bone-scans, CT-scans of lungs, etc. \n"
  method:
    llm:
      provider: openai #google
      model: gpt-4o #models/gemini-1.5-flash
      max_tokens: 4096
      system_prompt: "You are a faithful and truthful label extractor in the cardio medical/clinical domain. "
    ntm:
      model: nllb200
    out_per_instruction: True
  source_lang: en
  dest_lang: nl
  write_mode: w
  public_key_file: "/home/bramiozo/DEV/clinicalnlp-us.json"
  local_glossary_file: "config/glossary.csv"
