cleaning:
  min_sentence_character_length: 15
  max_sentence_length: 128
  sentence_delim: "[.:]"
  remove_characters: '[^-.,:\sA-z0-9]+'
  replace_characters:
    1: ["[0-9]{3,}", "###"]
    2: ["[0-9]{2}", "##"]
    3: ["[0-9]", "#"]
    4: ['\s{2,}', " "]
  write_mode: w
transformation:
  instructions:
    - "Rewrite this radiology text and structure it as a summary for the cardiologist"
    - "Extract the label: macrovascular disease / NO vascular disease"
  method:
    llm:
      provider: openai #google
      model: gpt-4o #models/gemini-1.5-flash
      max_tokens: 4096
      system_prompt: "You are a faithful and truthful label extractor in the medical/clinical domain. The user query is formatted as a dictionary {'instruction':...,  'text_to_label':..}, your response should ONLY consist of the label you extract."
    ntm:
      model: nllb200
    out_per_instruction: True
  source_lang: en
  dest_lang: nl
  write_mode: w
  public_key_file: "/home/bramiozo/DEV/clinicalnlp-us.json"
  local_glossary_file: "config/glossary.csv"
