cleaning:
  min_sentence_character_length: 15
  max_sentence_length: 128
  sentence_delim: "[.:]"
  remove_characters: '[^-.,:\sA-z0-9]+'
  replace_characters:
    1: ["[0-9]{3,}", "###"]
    2: ["[0-9]{2}", "##"]
    3: ["[0-9]", "#"]
    4: ['\s{2,}', " "]
  write_mode: w
transformation:
  instructions:
    - "Summarize the core message of this text in a few sentences."
    - "What is the general domain of this text. These are you possible domains [politics, sports, healthcare, entertainment, history, medical technology, medical science, other technology, other science, other]. Only respond with the domain."
  method:
    llm:
      endpoint: https://api.openai.com/v1/chat/completions #https://gemini.googleapis.com/v1/chat/completions
      provider: openai #google
      model: gpt-4o #models/gemini-1.5-flash
      max_tokens: 256
      system_prompt: "You are a faithful and truthful extractor of information."
    ntm:
      model: nllb200
    out_per_instruction: True
  source_lang: en
  dest_lang: nl
  write_mode: w
  public_key_file: "/home/bramiozo/DEV/clinicalnlp-us.json"
  local_glossary_file: "config/glossary.csv"
