inclusion_terms:
  ["cardiologie", "cardiale pathologie", "atherosclerose", "cardiomyopathie", "STEMI", "aderverkalking", "hartinfarct"]
exclusion_terms: ["feesten", "showbusiness", "huizen", "auto", "commercieel", "marketing", "winst", "liefde", "wrok"]
file_splitter:
  gigacorpus: r"[a-z0-9\-]{40,70}"
