cleaning:
  min_sentence_character_length: 15
  max_sentence_length: 128
  sentence_delim: '[.:]'
  remove_characters: '[^-.,:\sA-z0-9]+'
  replace_characters: 
    1: ['[0-9]{3,}', '###']
    2: ['[0-9]{2}', '##']
    3: ['[0-9]', '#']
    4: ['\s{2,}', ' ']
  write_mode: w
translation:
  source_lang: en
  dest_lang: nl
  method: public
  batch_size: 50
  write_mode: w
  public_key_file: '/home/bramiozo/DEV/clinicalnlp-us.json'
  local_glossary_file: 'config/glossary.csv'
  system_prompt: "You are a faithful and truthful translator in the medical/clinical domain. The user query is formatted as a dictionary {'source_language':.., 
  'target_language':.., 'text_to_translate':..}, your response should be: 'translated_text': YOUR_TRANSLATION"