cleaning:
  min_sentence_character_length: 15
  max_sentence_length: 128
  sentence_delim: "[.:]"
  remove_characters: '[^-.,:\sA-z0-9]+'
  replace_characters:
    1: ["[0-9]{3,}", "###"]
    2: ["[0-9]{2}", "##"]
    3: ["[0-9]", "#"]
    4: ['\s{2,}', " "]
  write_mode: w
transformation:
  instructions:
    - "Rewrite this Dutch radiology text and structure it as a pointwise summary for the cardiologist, focusing on any vascular or ischemic issues."
    - "We want to know whether a radiologist identifies macrovascular or functional heart disease. Specifically;  \n\n Macrovascular disease: a positive for macrovascular disease is any indication of the presence of 'significante stenosis', 'vaatlijden', 'stenosis >=50%', 'MESA > 75%', 'occlusie', 'atherosclerose', 'CADRADS >2', infarction.\n\n Functional disease: a positive for macrovascular disease is any indication of the presence of cardiomyopathy, perfusion defect, delayed enhancement, hypo perfusion, ischemic heart disease, Ejection Fraction (EF)<50%. Wandbewegingsstoornis(?) \n\n No vascular disease: if there is no indication of macrovascular or functional heart disease, or explicitly if the radiologist states that there is no vascular disease, or that the heart is normal, or the coronary arteries are normal, or that the scan is clean, or that nothing of interest was observed. \n\n Not related to cardiology: if the text is not related to cardiology, for example, if it is a report about a lung scan, a bone scam or a scan of the abdomen.  \n\n Uncertain: from the text none of the above labels can be ascertained \n\n Your task, extract the label: \n macrovascular disease / functional disease / No vascular disease / not related to cardiology / Uncertain.\n Note: it is possible that both macrovascular and functional heart disease are present. In that case, please flag both labels.\n Note: there might be a mentioning of a congenital heart disease such as PFO, VSD, ASD, Ductus van Botalli, septumdefect, coarctatio aortae or tetralogie van Fallot. But, as a long as these do not lead to macro/functional disease we ignore them.\n Note: in case of expressed doubt by the radiologist (“dubieus voor”, “vermoeden van”, “spoor van”) lean towards a positive label (i.e. Macrovascular disease/functional disease)."
  method:
    llm:
      endpoint: https://api.openai.com/v1/chat/completions #https://gemini.googleapis.com/v1/chat/completions
      provider: openai #google
      model: gpt-4o #models/gemini-1.5-flash
      max_tokens: 4096
      system_prompt: "You are a faithful and truthful label extractor in the cardio medical/clinical domain. "
    ntm:
      model: nllb200
    out_per_instruction: True
  source_lang: en
  dest_lang: nl
  write_mode: w
  public_key_file: "/home/bramiozo/DEV/clinicalnlp-us.json"
  local_glossary_file: "config/glossary.csv"
