cleaning:
  max_sentence_length: 512
  min_sentence_character_length: 25
  sentence_delim: '[:;.]'
  replace_characters: 
    - ['[0-9]', '#']
    - ['[0-9]{2}', '##']
    - ['[0-9]{3,}', '###']
    - ['\s{2,}', ' ']
    #- ['[^\x00-\x7F]+', ' ']
out:
  write_mode: w
  encoding: latin-1