inclusion_terms:
  - cardiologie
  - cardiale pathologie
  - atherosclerose
  - cardiomyopathie
  - aderverkalking
  - ziekteverloop
  - medicatie
  - pijnklachten
  - kortademigheid
  - bijwerkingen
  - excisie
  - incisie
  - pijnstilling
  - pijnstiller
  - hartinfarct
  - orthopedisch
  - reumatoide artritis
  - neuropathie
  - anatomie
  - anamnese
  - biopsie
  - anesthesie
  - inflammatie
  - weefselonderzoek
  - medicamenteus
  - oncologie
  - ziekte
  - diabetes
  - metastase
  - carcinoom
  - toxicologie
  - genetisch
  - pathologisch
  - pathologie
  - neurodegeneratie
  - NSTEMI
  - STEMI
  - hypertensie
  - tumor
  - ontstekingsremmer
  - prednison
  - prednisolon
  - proteoom
  - proteine
  - immunologie
  - psychiatrisch
  - patologisch
  - ontstekking
  - invasief
  - obesitas
  - artritis
  - artrose
  - chondrocalcinose
  - chronisch
  - prothese
  - medicijnen
  - inhalatie
exclusion_terms:
  [
    "feesten",
    "showbusiness",
    "huizen",
    "auto",
    "vrolijk",
    "leuk ",
    "lekker ",
    "heerlijk",
    "commercieel",
    "marketing",
    "webshop",
    "webwinkel",
    "aanbieding",
    "winst",
    "liefde",
    "wrok",
    "muziek",
  ]
file_splitter:
  gigacorpus: r"[a-z0-9\-]{40,70}"
