inclusion_terms:
  - cardiologie
  - cardiale pathologie
  - atherosclerose
  - cardiomyopathie
  - aderverkalking
  - ziekteverloop
  - medicatie
  - pijnklachten
  - kortademigheid
  - bijwerkingen
  - excisie
  - incisie
  - pijnstilling
  - pijnstiller
  - hartinfarct
  - orthopedisch
  - reumatoide artritis
  - neuropathie
  - anatomie
  - anamnese
  - biopsie
  - anesthesie
  - inflammatie
  - weefselonderzoek
  - medicamenteus
exclusion_terms:
  [
    "feesten",
    "showbusiness",
    "huizen",
    "auto",
    "vrolijk",
    "leuk ",
    "commercieel",
    "marketing",
    "winst",
    "liefde",
    "wrok",
    "muziek",
  ]
file_splitter:
  gigacorpus: r"[a-z0-9\-]{40,70}"
